### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Sasank-C**

### CODE REVIEW

**Comment by fulldecent** [comment]
Welcome to the party

**Comment by Sasank-C** [comment]
Thanks! Also, the Shasta faucet seems to be dry. Is there any workaround?

**Comment by fulldecent** [comment]
Paste it. I got you

**Comment by Sasank-C** [comment]
Found a working faucet channel in the [TRON Developer Discord](https://discord.gg/XgPzpGV3). Thanks anyway!

**Pull request merged**
